### ISSUE TITLE
elm watch a specific main file is broken

### ISSUE THREAD

**Issue by mbernerslee** [danturn/constant_testing#6]
(prior to the repo merge) you used to be able to do the equivalent of
`constant_testing ~/some/path/to/an/elm/Main.elm`

which would run 
`elm make ~/some/path/to/an/elm/Main.elm`
if any `.elm` file was changed

but now doing this is broken & it tried to do
`mix test ~/some/path/to/an/elm/Main.elm`

this makes me sad

**Comment by danturn** [comment]
Don't bring me problems bring me solutions!

**Comment by mbernerslee** [comment]
here's your solution
https://github.com/danturn/constant_testing/pull/7
